openapi: 3.0.0
info:
  title: Employee Management API
  description: API for managing employees
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /moods:
    post:
      summary: Create a new mood
      tags:
        - moods
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Mood"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mood"
  /moods/{id}:
    get:
      summary: Get a mood by ID
      tags:
        - moods
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mood"
  /students:
    get:
      summary: Get all students
      tags:
        - students
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Student"
    post:
      summary: Create a new student
      tags:
        - students
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
  /students/{id}:
    get:
      summary: Get a student by ID
      tags:
        - students
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
    put:
      summary: Update a student by ID
      tags:
        - students
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
    delete:
      summary: Delete a student by ID
      tags:
        - students
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: No Content
  /students/detailed:
    get:
      summary: Get detailed student information
      description: Returns students with their latest attendance and mood data
      operationId: getDetailedStudents
      tags:
        - students
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudentDetailedResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /dashboard:
    get:
      summary: Get student details for the dashboard
      description: Returns detailed student information including employer, attendance, and mood data.
      operationId: getStudentDetails
      tags:
        - dashboard
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudentCard"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /generate-otp:
    post:
      summary: Generate OTP for a student
      description: Generate a new OTP for a student
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: integer
                  example: 1
      responses:
        "200":
          description: OTP generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OTPResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /validate-otp:
    post:
      summary: Validate OTP
      description: Validate an OTP and generate a secret code
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp_code:
                  type: string
                  example: "1234"
      responses:
        "200":
          description: OTP validated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OTPValidationResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /verify-device-auth:
    post:
      summary: Verify device authorization
      description: Verify if a device is authorized using student ID and secret code
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: integer
                  example: 1
                secret_code:
                  type: string
                  example: "abcd1234"
      responses:
        "200":
          description: Device authorization verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorized:
                    type: boolean
                    example: true
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /employees:
    get:
      summary: Get all employees
      tags:
        - employees
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /location:
    post:
      summary: Update location
      description: Updates the location data for a student.
      tags:
        - location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longitude:
                  type: number
                  format: float
                latitude:
                  type: number
                  format: float
                address:
                  type: string
                studentId:
                  type: number
                  format: int64
      responses:
        "200":
          description: Location updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Location data received"
        "400":
          description: Invalid request body
        "401":
          description: Unauthorized
  /ws:
    get:
      summary: WebSocket connection for real-time updates
      description: Establishes a WebSocket connection to receive real-time location updates.
      tags:
        - websocket
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
  /attendance:
    post:
      summary: Create or update attendance record
      description: Handles check-in and check-out attendance records for students.
      tags:
        - attendance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                check_in:
                  type: boolean
                  description: Indicates if this is a check-in or check-out.
                check_in_lat:
                  type: number
                  format: float
                  description: Latitude for check-in.
                check_in_long:
                  type: number
                  format: float
                  description: Longitude for check-in.
      parameters:
        - name: Student-ID
          in: header
          required: true
          schema:
            type: integer
          description: The ID of the student.
        - name: Choreo-API-Key
          in: header
          required: true
          schema:
            type: string
          description: API key for authentication.
      responses:
        "200":
          description: Attendance record created or updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attendance"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Check-in record not found for today
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    Mood:
      type: object
      properties:
        emotion:
          type: string
        id:
          type: integer
        is_daily:
          type: boolean
        recorded_at:
          type: string
        student_id:
          type: integer
    Student:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        dob:
          type: string
          format: date
        gender:
          type: string
        address_line1:
          type: string
        address_line2:
          type: string
        city:
          type: string
        contact_number:
          type: string
        contact_number_guardian:
          type: string
        supervisor_id:
          type: integer
        employer_id:
          type: integer
        remarks:
          type: string
        photo:
          type: string
          format: byte
        home_long:
          type: number
          format: float
        home_lat:
          type: number
          format: float
    Attendance:
      type: object
      properties:
        id:
          type: integer
        student_id:
          type: integer
        date:
          type: string
        status:
          type: string
    StudentDetailedResponse:
      type: object
      properties:
        student_id:
          type: integer
          format: int64
          example: 12345
        first_name:
          type: string
          example: "John"
        last_name:
          type: string
          example: "Doe"
        employer_name:
          type: string
          example: "Acme Corp"
        check_in_date_time:
          type: string
          format: date-time
          example: "2023-05-01T08:30:00Z"
        check_out_date_time:
          type: string
          format: date-time
          example: "2023-05-01T17:30:00Z"
        emotion:
          type: string
          example: "happy"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Failed to retrieve student data"
    StudentCard:
      type: object
      properties:
        student_id:
          type: integer
          format: int64
          example: 12345
        first_name:
          type: string
          example: "John"
        last_name:
          type: string
          example: "Doe"
        employer_name:
          type: string
          nullable: true
          example: "Acme Corp"
        check_in_date_time:
          type: string
          format: date-time
          example: "2023-05-01T08:30:00Z"
        check_out_date_time:
          type: string
          format: date-time
          example: "2023-05-01T17:30:00Z"
        emotion:
          type: string
          example: "happy"
    OTPResponse:
      type: object
      properties:
        student_id:
          type: integer
          example: 1
        otp_code:
          type: string
          example: "1234"
        expires_at:
          type: string
          format: date-time
          example: "2025-04-30T15:30:00Z"
    OTPValidationResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Authentication successful"
        token:
          type: string
          example: "abcd1234"
    Employee:
      type: object
      properties:
        student_id:
          type: integer
        student_name:
          type: string
        student_contact:
          type: string
        employer_id:
          type: integer
          nullable: true
        employer_name:
          type: string
          nullable: true
        employer_contact:
          type: string
          nullable: true
        employer_address:
          type: string
          nullable: true
        supervisor_id:
          type: integer
          nullable: true
        supervisor_name:
          type: string
          nullable: true
        latest_otp_code:
          type: string
          nullable: true
        expires_at:
          type: string
          format: date-time
          nullable: true
