openapi: 3.0.0
info:
  title: Employee Management API
  description: API for managing employees and authentication
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /generate-otp:
    post:
      summary: Generate OTP for a student
      description: Generate a new OTP for a student
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: integer
                  example: 1
      responses:
        "200":
          description: OTP generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OTPResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /validate-otp:
    post:
      summary: Validate OTP
      description: Validate an OTP and generate a secret code
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp_code:
                  type: string
                  example: "1234"
      responses:
        "200":
          description: OTP validated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OTPValidationResponse"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /verify-device-auth:
    post:
      summary: Verify device authorization
      description: Verify if a device is authorized using student ID and secret code
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: integer
                  example: 1
                secret_code:
                  type: string
                  example: "abcd1234"
      responses:
        "200":
          description: Device authorization verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorized:
                    type: boolean
                    example: true
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    OTPResponse:
      type: object
      properties:
        student_id:
          type: integer
          example: 1
        otp_code:
          type: string
          example: "1234"
        expires_at:
          type: string
          format: date-time
          example: "2025-04-30T15:30:00Z"
    OTPValidationResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        student_id:
          type: integer
          example: 1
        secret_code:
          type: string
          example: "abcd1234"
        message:
          type: string
          example: "Authentication successful"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Invalid request payload"
