swagger: "2.0"
info:
  title: API Documentation
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

definitions:
  Mood:
    type: object
    properties:
      emotion:
        type: string
      id:
        type: integer
      is_daily:
        type: boolean
      recorded_at:
        type: string
      student_id:
        type: integer

  Student:
    type: object
    properties:
      address_line1:
        type: string
      address_line2:
        type: string
      city:
        type: string
      contact_number:
        type: string
      contact_number_guardian:
        type: string
      dob:
        type: string
      employer_id:
        type: integer
      first_name:
        type: string
      gender:
        type: string
      home_coordinates:
        type: string
      id:
        type: integer
      last_name:
        type: string
      photo:
        type: array
        items:
          type: integer
      remarks:
        type: string
      supervisor_id:
        type: integer

  Supervisor:
    type: object
    properties:
      contact_number:
        type: string
      email_address:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      student_id:
        type: integer
      supervisor_id:
        type: integer

paths:
  /moods:
    get:
      consumes:
        - application/json
      description: Get details of all moods
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Mood'
      summary: Get all moods
      tags:
        - moods
    post:
      consumes:
        - application/json
      description: Create a new mood
      parameters:
        - in: body
          name: mood
          description: Mood object
          required: true
          schema:
            $ref: '#/definitions/Mood'
      produces:
        - application/json
      responses:
        "200":
          description: Created
          schema:
            $ref: '#/definitions/Mood'
      summary: Create a new mood
      tags:
        - moods

  /moods/{id}:
    get:
      consumes:
        - application/json
      description: Get a mood by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Mood'
      summary: Get a mood by ID
      tags:
        - moods

  /students:
    get:
      consumes:
        - application/json
      description: Get all students
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Student'
      summary: Get all students
      tags:
        - students
    post:
      consumes:
        - application/json
      description: Create a new student
      parameters:
        - in: body
          name: student
          required: true
          schema:
            $ref: '#/definitions/Student'
      produces:
        - application/json
      responses:
        "200":
          description: Created
          schema:
            $ref: '#/definitions/Student'
      summary: Create a new student
      tags:
        - students

  /students/{id}:
    get:
      consumes:
        - application/json
      description: Get a student by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Student'
      summary: Get a student by ID
      tags:
        - students
    put:
      consumes:
        - application/json
      description: Update a student by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: student
          required: true
          schema:
            $ref: '#/definitions/Student'
      produces:
        - application/json
      responses:
        "200":
          description: Updated
          schema:
            $ref: '#/definitions/Student'
      summary: Update a student by ID
      tags:
        - students
    delete:
      consumes:
        - application/json
      description: Delete a student by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      summary: Delete a student by ID
      tags:
        - students

  /supervisors:
    get:
      consumes:
        - application/json
      description: Get all supervisors
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Supervisor'
      summary: Get all supervisors
      tags:
        - supervisors
    post:
      consumes:
        - application/json
      description: Create a new supervisor
      parameters:
        - in: body
          name: supervisor
          required: true
          schema:
            $ref: '#/definitions/Supervisor'
      produces:
        - application/json
      responses:
        "200":
          description: Created
          schema:
            $ref: '#/definitions/Supervisor'
      summary: Create a new supervisor
      tags:
        - supervisors

  /supervisors/{id}:
    get:
      consumes:
        - application/json
      description: Get a supervisor by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Supervisor'
      summary: Get a supervisor by ID
      tags:
        - supervisors
    put:
      consumes:
        - application/json
      description: Update a supervisor by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
        - in: body
          name: supervisor
          required: true
          schema:
            $ref: '#/definitions/Supervisor'
      produces:
        - application/json
      responses:
        "200":
          description: Updated
          schema:
            $ref: '#/definitions/Supervisor'
      summary: Update a supervisor by ID
      tags:
        - supervisors
    delete:
      consumes:
        - application/json
      description: Delete a supervisor by ID
      parameters:
        - in: path
          name: id
          required: true
          type: integer
      responses:
        "204":
          description: No Content
      summary: Delete a supervisor by ID
      tags:
        - supervisors
